(function(global){
  'use strict';

  const LETTERS=['A','B','C','D','E','F'];
  const clone=x=>JSON.parse(JSON.stringify(x));
  const key=x=>JSON.stringify(x);

  function rng(seed){
    return function(){
      seed|=0;seed=seed+0x6D2B79F5|0;
      let t=Math.imul(seed^seed>>>15,1|seed);
      t=t+Math.imul(t^t>>>7,61|t)^t;
      return((t^t>>>14)>>>0)/4294967296;
    };
  }
  function makeContext(seed){
    const R=rng(seed||20260731);
    const ri=(a,b)=>Math.floor(R()*(b-a+1))+a;
    const nz=(a=-7,b=7)=>{let x=0;while(!x)x=ri(a,b);return x;};
    const pick=a=>a[Math.floor(R()*a.length)];
    const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(R()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
    const sign=n=>n>=0?`+${n}`:`${n}`;
    return{R,ri,nz,pick,shuffle,sign};
  }

  const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const t=a%b;a=b;b=t;}return a||1;};
  function texNum(value){
    const x=Number(value);if(!Number.isFinite(x))return String(value);if(Number.isInteger(x))return String(x);
    let den=1,num=Math.round(x),found=false;
    for(let d=2;d<=240;d++){const n=Math.round(x*d);if(Math.abs(x-n/d)<1e-10){num=n;den=d;found=true;break;}}
    if(!found){den=10000;num=Math.round(x*den);}
    const g=gcd(num,den);num/=g;den/=g;const s=num<0?'-':'';num=Math.abs(num);
    return den===1?`${s}${num}`:`${s}\\frac{${num}}{${den}}`;
  }
  const math=s=>String.raw`\(${s}\)`;
  const display=s=>String.raw`\[${s}\]`;
  const v2=v=>String.raw`\left(${texNum(v[0])},${texNum(v[1])}\right)`;
  const v3=v=>String.raw`\left(${texNum(v[0])},${texNum(v[1])},${texNum(v[2])}\right)`;
  const mtex=m=>String.raw`\begin{bmatrix}${m.map(r=>r.map(texNum).join('&')).join('\\\\')}\end{bmatrix}`;
  const atex=m=>String.raw`\left[\begin{array}{${'c'.repeat(m[0].length-1)}|c}${m.map(r=>r.map(texNum).join('&')).join('\\\\')}\end{array}\right]`;
  const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);
  const norm2=a=>dot(a,a);
  const addV=(a,b)=>a.map((x,i)=>x+b[i]);
  const subV=(a,b)=>a.map((x,i)=>x-b[i]);
  const scaleV=(c,a)=>a.map(x=>c*x);
  const transpose=A=>A[0].map((_,j)=>A.map(r=>r[j]));
  const matAdd=(A,B)=>A.map((r,i)=>r.map((x,j)=>x+B[i][j]));
  const matScale=(c,A)=>A.map(r=>r.map(x=>c*x));
  const matMul=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)));
  const matVec=(A,x)=>A.map(r=>dot(r,x));
  const det2=A=>A[0][0]*A[1][1]-A[0][1]*A[1][0];
  const det3=A=>A[0][0]*(A[1][1]*A[2][2]-A[1][2]*A[2][1])-A[0][1]*(A[1][0]*A[2][2]-A[1][2]*A[2][0])+A[0][2]*(A[1][0]*A[2][1]-A[1][1]*A[2][0]);
  const sameMatrix=(A,B)=>key(A)===key(B);

  function optionSet(correct,distractors,formatter=x=>String(x),shuffle=x=>x){
    const vals=[];const push=v=>{if(!vals.some(z=>key(z)===key(v)))vals.push(clone(v));};
    [correct,...distractors].forEach(push);
    let n=1,guard=0;
    while(vals.length<6&&guard++<150){
      let c;
      if(typeof correct==='number')c=correct+(n%2?n:-n);
      else if(Array.isArray(correct)){c=clone(correct);if(Array.isArray(c[0]))c[0][0]+=n;else c[0]+=n;}
      else c=`${correct} ${n}`;
      push(c);n++;
    }
    const mixed=shuffle(vals.slice(0,6));
    return{options:mixed.map((v,i)=>({letter:LETTERS[i],html:formatter(v),value:i})),answer:mixed.findIndex(v=>key(v)===key(correct))};
  }
  function comboOptions(correct,choices,shuffle){
    const vals=[];[correct,...choices].forEach(x=>{if(!vals.includes(x))vals.push(x);});
    const mixed=shuffle(vals.slice(0,6));
    return{options:mixed.map((x,i)=>({letter:LETTERS[i],html:x,value:i})),answer:mixed.indexOf(correct)};
  }
  function base(level,topic,difficulty,type,badge,template,rest){return{level,topic,difficulty,type,badge,template,...rest};}
  function inv2(A){const d=det2(A);return[[A[1][1]/d,-A[0][1]/d],[-A[1][0]/d,A[0][0]/d]];}
  function invertible2(c){let A;do{A=[[c.nz(-5,5),c.nz(-5,5)],[c.nz(-5,5),c.nz(-5,5)]];}while(Math.abs(det2(A))<1);return A;}
  function invertible3(c){let A;do{A=Array.from({length:3},()=>Array.from({length:3},()=>c.ri(-4,4)));}while(!det3(A)||Math.abs(det3(A))>80);return A;}
  function pythagorean2(c){const triples=[[3,4,5],[5,12,13],[8,15,17],[7,24,25]];const [a,b,n]=c.pick(triples),scale=c.ri(1,4);const signs=[c.pick([-1,1]),c.pick([-1,1])];return{v:[scale*a*signs[0],scale*b*signs[1]],n:scale*n};}
  function pythagorean3(c){const choices=[[1,2,2,3],[2,3,6,7],[2,6,9,11],[4,4,7,9]];const [a,b,d,n]=c.pick(choices),scale=c.ri(1,3);return{v:[scale*a*c.pick([-1,1]),scale*b*c.pick([-1,1]),scale*d*c.pick([-1,1])],n:scale*n};}
  function system3FromSolution(c){const A=invertible3(c),x=[c.ri(-4,6),c.ri(-4,6),c.ri(-4,6)],b=matVec(A,x);return{A,x,b,M:A.map((r,i)=>[...r,b[i]])};}

  const T={};

  // MUNDO 1 · VECTORES EN R2
  T.v2_combo=c=>{const u=[c.nz(),c.nz()],v=[c.nz(),c.nz()],a=c.pick([-3,-2,2,3,4]),b=c.pick([-3,-2,2,3]),ans=addV(scaleV(a,u),scaleV(b,v));return base(1,'v2d-ops',1,'mcq','NIVEL 1 · COMBINACIÓN VECTORIAL','v2_combo',{prompt:`Sean ${math(`\\mathbf u=${v2(u)}`)} y ${math(`\\mathbf v=${v2(v)}`)}. Calcule ${math(`${a}\\mathbf u${b>=0?'+':''}${b}\\mathbf v`)}.`,...optionSet(ans,[addV(scaleV(a,u),scaleV(-b,v)),addV(scaleV(b,u),scaleV(a,v)),[ans[1],ans[0]],[-ans[0],ans[1]],[ans[0],-ans[1]]],x=>math(v2(x)),c.shuffle),hint:`Calcula ${math(`${a}\\mathbf u`)} y ${math(`${b}\\mathbf v`)} por separado y combina componentes homólogas.`,explanation:display(`${a}\\mathbf u${b>=0?'+':''}${b}\\mathbf v=${v2(ans)}.`),visual:{kind:'vectors',u,v,result:ans},instruction:'Programa el impulso resultante componente a componente.'});};
  T.v2_norm_unit=c=>{const {v,n}=pythagorean2(c),unit=v.map(x=>x/n),twice=scaleV(2,v);const statements=[`${math(`\\|\\mathbf u\\|=${n}`)}`,`${math(`\\widehat{\\mathbf u}=${v2(unit)}`)}`,`${math(`2\\mathbf u=${v2(twice)}`)}`,'El vector opuesto tiene el mismo sentido.'];return base(1,'v2d-geometry',1,'roman','NIVEL 1 · NORMA Y DIRECCIÓN','v2_norm_unit',{prompt:`Para ${math(`\\mathbf u=${v2(v)}`)}, determine cuáles afirmaciones son correctas:<ol class="roman-list" type="I">${statements.map(x=>`<li>${x}</li>`).join('')}</ol>`,...comboOptions('I, II y III',['I y II','II y IV','I, III y IV','II y III','Todas'],c.shuffle),hint:'Calcula la norma, divide por ella y distingue dirección de sentido.',explanation:`I, II y III son correctas. El vector opuesto conserva la dirección, pero invierte el sentido.`,visual:{kind:'vectors',u:v,v:scaleV(-1,v)},instruction:'Verifica la geometría del vector antes de avanzar.'});};
  T.v2_norm_param=c=>{const {v,n}=pythagorean2(c),idx=c.ri(0,1),known=v[1-idx],ans=Math.abs(v[idx]);const vector=idx===0?['k',known]:[known,'k'];return base(1,'v2d-geometry',2,'numeric','NIVEL 1 · PARÁMETRO DE NORMA','v2_norm_param',{prompt:`El vector ${math(`\\mathbf v=(${vector[0]},${vector[1]})`)} tiene norma ${math(String(n))} y ${math('k>0')}. Determine ${math('k')}.`,answerValue:ans,hint:`Usa ${math(`k^2+${known}^2=${n}^2`)} y toma la raíz positiva.`,explanation:display(`k=\\sqrt{${n*n}-${known*known}}=${ans}.`),visual:{kind:'vectors',u:idx===0?[ans,known]:[known,ans],v:[0,0]},instruction:'Ajusta el parámetro que fija la longitud.'});};
  T.v2_orth_param=c=>{const b=c.nz(-6,6),d=c.nz(-6,6),a=c.pick([-4,-3,-2,2,3,4]),k=-(a*d)/b;if(!Number.isInteger(k))return T.v2_orth_param(makeContext((c.ri(1,1e9))));const u=[k,a],v=[b,d];return base(1,'v2d-geometry',2,'numeric','NIVEL 1 · ORTOGONALIDAD PARAMÉTRICA','v2_orth_param',{prompt:`Determine ${math('k')} para que ${math(v2(['k',a]))} y ${math(v2(v))} sean perpendiculares.`,answerValue:k,hint:'La perpendicularidad exige producto punto igual a cero.',explanation:display(`${b}k+(${a})(${d})=0\\Longrightarrow k=${k}.`),visual:{kind:'vectors',u,v},instruction:'Fija un ángulo de noventa grados.'});};
  T.v2_direction=c=>{const u=[c.nz(),c.nz()],lambda=c.pick([-4,-3,-2,2,3,4]),v=scaleV(lambda,u),same=lambda>0;return base(1,'v2d-ops',2,'tf','NIVEL 1 · DIRECCIÓN Y SENTIDO','v2_direction',{prompt:`Los vectores ${math(`\\mathbf u=${v2(u)}`)} y ${math(`\\mathbf v=${v2(v)}`)} tienen la misma dirección y el mismo sentido.`,answer:same,hint:'Expresa un vector como múltiplo escalar del otro y revisa el signo.',explanation:`${math(`\\mathbf v=${lambda}\\mathbf u`)}. ${same?'El escalar positivo conserva el sentido.':'El escalar negativo invierte el sentido.'}`,visual:{kind:'vectors',u,v},instruction:'Clasifica la relación direccional.'});};
  T.v2_projection=c=>{const b=c.pick([[1,0],[0,1],[1,1],[1,-1],[2,1],[1,2]]),t=c.nz(-5,5),w=c.pick([[1,-1],[2,-2],[-1,1],[2,-1],[-2,1]]),perp=[-b[1]*w[0],b[0]*w[0]],a=addV(scaleV(t,b),perp),coef=dot(a,b)/norm2(b),proj=scaleV(coef,b);return base(1,'v2d-geometry',3,'mcq','NIVEL 1 · PROYECCIÓN','v2_projection',{prompt:`Calcule ${math(`\\operatorname{proj}_{\\mathbf b}(\\mathbf a)`)} para ${math(`\\mathbf a=${v2(a)}`)} y ${math(`\\mathbf b=${v2(b)}`)}.`,...optionSet(proj,[a,b,subV(a,proj),scaleV(-1,proj),[proj[1],proj[0]]],x=>math(v2(x)),c.shuffle),hint:`Aplica ${math('\\operatorname{proj}_{\\mathbf b}(\\mathbf a)=\\frac{\\mathbf a\\cdot\\mathbf b}{\\|\\mathbf b\\|^2}\\mathbf b')}.`,explanation:display(`\\frac{\\mathbf a\\cdot\\mathbf b}{\\|\\mathbf b\\|^2}=${texNum(coef)},\\qquad \\operatorname{proj}_{\\mathbf b}(\\mathbf a)=${v2(proj)}.`),visual:{kind:'projection',a,b,proj},instruction:'Alinea la trayectoria mediante una proyección.'});};
  T.v2_work=c=>{const F=[c.ri(-40,60),c.ri(-40,60)],d=[c.nz(-8,8),c.nz(-8,8)],W=dot(F,d);return base(1,'v2d-ops',3,'numeric','NIVEL 1 · TRABAJO VECTORIAL','v2_work',{prompt:`Una fuerza ${math(`\\mathbf F=${v2(F)}\\,\\mathrm N`)} produce el desplazamiento ${math(`\\mathbf d=${v2(d)}\\,\\mathrm m`)}. Calcule ${math('W=\\mathbf F\\cdot\\mathbf d')}.`,answerValue:W,hint:'Multiplica componentes correspondientes y suma.',explanation:display(`W=${F[0]}(${d[0]})+${F[1]}(${d[1]})=${W}\\,\\mathrm J.`),visual:{kind:'vectors',u:F,v:d},instruction:'Calcula la energía transferida.'});};
  T.v2_difference_norm=c=>{const {v:u,n:nu}=pythagorean2(c),v=[c.nz(),c.nz()],d=dot(u,v),ans=nu*nu+norm2(v)-2*d;return base(1,'v2d-geometry',4,'numeric','NIVEL 1 · IDENTIDAD DE NORMA','v2_difference_norm',{prompt:`Sean ${math(`\\|\\mathbf u\\|=${nu}`)}, ${math(`\\mathbf v=${v2(v)}`)} y ${math(`\\mathbf u\\cdot\\mathbf v=${d}`)}. Calcule ${math('\\|\\mathbf u-\\mathbf v\\|^2')}.`,answerValue:ans,hint:'Expande la norma al cuadrado de la diferencia.',explanation:display(`\\|\\mathbf u-\\mathbf v\\|^2=${nu}^2+${norm2(v)}-2(${d})=${ans}.`),instruction:'Determina la separación cuadrática.'});};
  T.v2_displacement=c=>{const P=[c.ri(-8,8),c.ri(-8,8)],D=[c.nz(-8,8),c.nz(-8,8)],Q=addV(P,D),ans=norm2(D);return base(1,'v2d-ops',2,'numeric','NIVEL 1 · DESPLAZAMIENTO','v2_displacement',{prompt:`Una nave se mueve de ${math(`P=${v2(P)}`)} a ${math(`Q=${v2(Q)}`)}. Calcule ${math('\\|\\overrightarrow{PQ}\\|^2')}.`,answerValue:ans,hint:'Primero forma \\(Q-P\\), después calcula la norma al cuadrado.',explanation:display(`\\overrightarrow{PQ}=${v2(D)},\\qquad \\|\\overrightarrow{PQ}\\|^2=${ans}.`),visual:{kind:'vectors',u:P,v:Q,result:D},instruction:'Mide el desplazamiento exacto.'});};
  T.v2_dot_angle=c=>{const u=c.pick([[1,0],[0,1],[1,1],[1,-1],[2,1]]),lambda=c.pick([2,3,4]),perp=[-u[1],u[0]],v=addV(scaleV(lambda,u),scaleV(c.pick([-2,-1,1,2]),perp)),ans=dot(u,v);return base(1,'v2d-geometry',3,'numeric','NIVEL 1 · PRODUCTO PUNTO','v2_dot_angle',{prompt:`Para ${math(`\\mathbf u=${v2(u)}`)} y ${math(`\\mathbf v=${v2(v)}`)}, calcule ${math('\\mathbf u\\cdot\\mathbf v')}.`,answerValue:ans,hint:'Multiplica las componentes correspondientes.',explanation:display(`\\mathbf u\\cdot\\mathbf v=${u[0]}(${v[0]})+${u[1]}(${v[1]})=${ans}.`),visual:{kind:'vectors',u,v},instruction:'Calcula la afinidad angular de las rutas.'});};

  // MUNDO 2 · VECTORES EN R3
  T.v3_combo=c=>{const u=[c.nz(),c.nz(),c.nz()],v=[c.nz(),c.nz(),c.nz()],a=c.pick([-3,-2,2,3]),b=c.pick([-2,-1,1,2]),ans=addV(scaleV(a,u),scaleV(b,v));return base(2,'v3d-ops',1,'mcq','NIVEL 2 · COMBINACIÓN EN R³','v3_combo',{prompt:`Sean ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(v)}`)}. Calcule ${math(`${a}\\mathbf u${b>=0?'+':''}${b}\\mathbf v`)}.`,...optionSet(ans,[addV(scaleV(a,u),scaleV(-b,v)),addV(scaleV(b,u),scaleV(a,v)),[ans[1],ans[0],ans[2]],[-ans[0],ans[1],ans[2]],[ans[0],ans[1],-ans[2]]],x=>math(v3(x)),c.shuffle),hint:'Opera cada una de las tres componentes.',explanation:display(`${a}\\mathbf u${b>=0?'+':''}${b}\\mathbf v=${v3(ans)}.`),visual:{kind:'vectors',u:u.slice(0,2),v:v.slice(0,2),result:ans.slice(0,2)},instruction:'Combina tres componentes de navegación.'});};
  T.v3_norm_param=c=>{const {v,n}=pythagorean3(c),idx=c.ri(0,2),known=v.map((x,i)=>i===idx?'k':x),ans=Math.abs(v[idx]),sum=v.reduce((s,x,i)=>i===idx?s:s+x*x,0);return base(2,'v3d-dot',2,'numeric','NIVEL 2 · NORMA PARAMÉTRICA','v3_norm_param',{prompt:`El vector ${math(`\\mathbf u=${v3(known)}`)} tiene norma ${math(String(n))} y ${math('k>0')}. Determine ${math('k')}.`,answerValue:ans,hint:`Plantea ${math(`k^2+${sum}=${n*n}`)}.`,explanation:display(`k=\\sqrt{${n*n}-${sum}}=${ans}.`),instruction:'Completa la coordenada faltante.'});};
  T.v3_dot=c=>{const u=[c.nz(),c.nz(),c.nz()],v=[c.nz(),c.nz(),c.nz()],ans=dot(u,v);return base(2,'v3d-dot',1,'numeric','NIVEL 2 · PRODUCTO PUNTO 3D','v3_dot',{prompt:`Calcule ${math('\\mathbf u\\cdot\\mathbf v')} para ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(v)}`)}.`,answerValue:ans,hint:'Suma los tres productos componente a componente.',explanation:display(`\\mathbf u\\cdot\\mathbf v=${u[0]}(${v[0]})+${u[1]}(${v[1]})+${u[2]}(${v[2]})=${ans}.`),instruction:'Sincroniza las trayectorias tridimensionales.'});};
  T.v3_orth_param=c=>{const a=c.nz(-4,4),b=c.nz(-4,4),p=c.nz(-5,5),q=c.nz(-5,5),r=c.nz(-5,5);let k=-(a*p+b*q)/r;if(!Number.isInteger(k))return T.v3_orth_param(makeContext(c.ri(1,1e9)));const u=[a,b,k],v=[p,q,r];return base(2,'v3d-dot',2,'numeric','NIVEL 2 · ORTOGONALIDAD 3D','v3_orth_param',{prompt:`Determine ${math('k')} para que ${math(`(${a},${b},k)`)} sea perpendicular a ${math(v3(v))}.`,answerValue:k,hint:'Iguala el producto punto a cero.',explanation:display(`${a}(${p})+${b}(${q})+k(${r})=0\\Longrightarrow k=${k}.`),instruction:'Ajusta el vector hasta hacerlo ortogonal.'});};
  T.v3_pythagoras_tf=c=>{const u=[c.nz(-4,4),c.nz(-4,4),c.nz(-4,4)],w=[c.nz(-3,3),c.nz(-3,3),c.nz(-3,3)],v=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]],truth=c.pick([true,false]);const vv=truth?v:addV(v,[1,0,0]);return base(2,'v3d-dot',2,'tf','NIVEL 2 · IDENTIDAD DE PITÁGORAS','v3_pythagoras_tf',{prompt:`Para ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(vv)}`)}, se cumple ${math('\\|\\mathbf u+\\mathbf v\\|^2=\\|\\mathbf u\\|^2+\\|\\mathbf v\\|^2')}.`,answer:dot(u,vv)===0,hint:'La igualdad se cumple exactamente cuando el producto punto es cero.',explanation:`${math(`\\mathbf u\\cdot\\mathbf v=${dot(u,vv)}`)}; por tanto, la afirmación es ${dot(u,vv)===0?'verdadera':'falsa'}.`,instruction:'Comprueba la ortogonalidad oculta.'});};
  T.v3_distance=c=>{const P=[c.ri(-6,6),c.ri(-6,6),c.ri(-6,6)],D=c.pick([[1,2,2],[2,3,6],[2,6,9],[4,4,7]]).map(x=>x*c.pick([-1,1])),Q=addV(P,D),ans=Math.sqrt(norm2(D));return base(2,'v3d-ops',2,'numeric','NIVEL 2 · DISTANCIA ESPACIAL','v3_distance',{prompt:`Determine la distancia entre ${math(`P=${v3(P)}`)} y ${math(`Q=${v3(Q)}`)}.`,answerValue:ans,hint:'Forma \\(Q-P\\) y calcula su norma.',explanation:display(`Q-P=${v3(D)},\\qquad d(P,Q)=\\sqrt{${norm2(D)}}=${ans}.`),instruction:'Calcula la distancia en el espacio.'});};
  T.v3_work=c=>{const F=[c.nz(-8,8),c.nz(-8,8),c.nz(-8,8)],d=[c.nz(-6,6),c.nz(-6,6),c.nz(-6,6)],ans=dot(F,d);return base(2,'v3d-dot',3,'numeric','NIVEL 2 · TRABAJO EN R³','v3_work',{prompt:`Una fuerza ${math(`\\mathbf F=${v3(F)}`)} actúa durante el desplazamiento ${math(`\\mathbf d=${v3(d)}`)}. Calcule el trabajo.`,answerValue:ans,hint:'Evalúa el producto punto en tres dimensiones.',explanation:display(`W=\\mathbf F\\cdot\\mathbf d=${ans}.`),instruction:'Determina el trabajo tridimensional.'});};
  T.v3_projection_component=c=>{const v=c.pick([[1,1,1],[1,1,-1],[2,1,1],[1,2,1]]),t=c.nz(-4,4),p=[v[1],-v[0],0],u=addV(scaleV(t,v),scaleV(c.nz(-3,3),p)),coef=dot(u,v)/norm2(v),proj=scaleV(coef,v),idx=c.ri(0,2);return base(2,'v3d-dot',4,'numeric','NIVEL 2 · PROYECCIÓN 3D','v3_projection_component',{prompt:`Sean ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(v)}`)}. Calcule la componente ${idx+1} de ${math('\\operatorname{proj}_{\\mathbf v}(\\mathbf u)')}.`,answerValue:proj[idx],hint:'Calcula el coeficiente de proyección y luego multiplica por \\(\\mathbf v\\).',explanation:display(`\\operatorname{proj}_{\\mathbf v}(\\mathbf u)=${v3(proj)},\\qquad \\text{componente ${idx+1}}=${texNum(proj[idx])}.`),instruction:'Extrae una coordenada de la proyección.'});};
  T.v3_linear_param=c=>{const u=[c.nz(-4,4),c.nz(-4,4),c.nz(-4,4)];let v;do{v=[c.nz(-4,4),c.nz(-4,4),c.nz(-4,4)];}while((u[0]*v[1]-u[1]*v[0])===0&&(u[0]*v[2]-u[2]*v[0])===0&&(u[1]*v[2]-u[2]*v[1])===0);const a=c.nz(-4,4),b=c.nz(-4,4),w=addV(scaleV(a,u),scaleV(b,v)),ask=c.pick(['a','b']);return base(2,'v3d-ops',3,'numeric','NIVEL 2 · COEFICIENTE DE COMBINACIÓN','v3_linear_param',{prompt:`Se sabe que ${math(`a\\mathbf u+b\\mathbf v=${v3(w)}`)}, donde ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(v)}`)}. Determine ${math(ask)}.`,answerValue:ask==='a'?a:b,hint:'Usa dos componentes para resolver el sistema de coeficientes y verifica con la tercera.',explanation:display(`a=${a},\\qquad b=${b}.`),instruction:'Recupera el coeficiente de la combinación.'});};
  T.v3_sum_norm=c=>{const u=[c.nz(),c.nz(),c.nz()],v=[c.nz(),c.nz(),c.nz()],ans=norm2(addV(u,v));return base(2,'v3d-dot',3,'numeric','NIVEL 2 · NORMA DE LA RESULTANTE','v3_sum_norm',{prompt:`Calcule ${math('\\|\\mathbf u+\\mathbf v\\|^2')} para ${math(`\\mathbf u=${v3(u)}`)} y ${math(`\\mathbf v=${v3(v)}`)}.`,answerValue:ans,hint:'Suma primero los vectores y luego calcula la norma al cuadrado.',explanation:display(`\\mathbf u+\\mathbf v=${v3(addV(u,v))},\\qquad \\|\\mathbf u+\\mathbf v\\|^2=${ans}.`),instruction:'Mide la intensidad de la resultante.'});};

  // MUNDO 3 · MATRICES
  T.m_combo=c=>{const A=Array.from({length:2},()=>[c.ri(-5,5),c.ri(-5,5)]),B=Array.from({length:2},()=>[c.ri(-5,5),c.ri(-5,5)]),a=c.pick([-3,-2,2,3]),b=c.pick([-2,-1,1,2]),C=matAdd(matScale(a,A),matScale(b,B));return base(3,'m22-ops',1,'mcq','NIVEL 3 · COMBINACIÓN DE MATRICES','m_combo',{prompt:`Sean ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Calcule ${math(`${a}A${b>=0?'+':''}${b}B`)}.`,...optionSet(C,[matAdd(matScale(a,A),matScale(-b,B)),matAdd(matScale(b,A),matScale(a,B)),transpose(C),matScale(-1,C),A],x=>math(mtex(x)),c.shuffle),hint:'Opera entrada por entrada y controla los signos.',explanation:display(`${a}A${b>=0?'+':''}${b}B=${mtex(C)}.`),visual:{kind:'matrixMultiply',A,B,C},instruction:'Combina los módulos matriciales.'});};
  T.m_product_entry=c=>{const A=Array.from({length:2},()=>[c.ri(-5,5),c.ri(-5,5)]),B=Array.from({length:2},()=>[c.ri(-5,5),c.ri(-5,5)]),C=matMul(A,B),i=c.ri(0,1),j=c.ri(0,1);return base(3,'m22-ops',2,'numeric','NIVEL 3 · ENTRADA DE UN PRODUCTO','m_product_entry',{prompt:`Sean ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Determine ${math(`(AB)_{${i+1}${j+1}}`)}.`,answerValue:C[i][j],hint:`Multiplica la fila ${i+1} de \\(A\\) por la columna ${j+1} de \\(B\\).`,explanation:display(`(AB)_{${i+1}${j+1}}=${A[i].map((x,k)=>`${x}(${B[k][j]})`).join('+')}=${C[i][j]}.`),visual:{kind:'matrixMultiply',A,B,C},instruction:'Calcula una entrada por fila y columna.'});};
  T.m_commute_tf=c=>{const diagonal=c.pick([true,false]);let A,B;if(diagonal){A=[[c.nz(),0],[0,c.nz()]];B=[[c.nz(),0],[0,c.nz()]];}else{A=[[1,c.nz()],[0,1]];B=[[1,0],[c.nz(),1]];}const truth=sameMatrix(matMul(A,B),matMul(B,A));return base(3,'m22-ops',2,'tf','NIVEL 3 · CONMUTATIVIDAD','m_commute_tf',{prompt:`Para ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}, se cumple ${math('AB=BA')}.`,answer:truth,hint:'Calcula ambos productos en el orden indicado.',explanation:`${math(`AB=${mtex(matMul(A,B))}`)} y ${math(`BA=${mtex(matMul(B,A))}`)}; la afirmación es ${truth?'verdadera':'falsa'}.`,visual:{kind:'matrixMultiply',A,B,C:matMul(A,B)},instruction:'Comprueba si el orden altera el producto.'});};
  T.m_dimensions=c=>{const m=c.ri(2,6),n=c.ri(2,6);let p=c.ri(2,6);while(p===m)p=c.ri(2,6);const statements=[`${math(`\\displaystyle A\\in M_{${m}\\times${n}}`)} y ${math(`\\displaystyle B\\in M_{${n}\\times${p}}`)} permiten calcular ${math('AB')}.`,`${math(`AB\\in M_{${m}\\times${p}}`)}.`,`${math(`B^T\\in M_{${p}\\times${n}}`)}.`,`${math('BA')} siempre está definido.`];return base(3,'m33-ops',1,'roman','NIVEL 3 · DIMENSIONES MATRICIALES','m_dimensions',{prompt:`Determine cuáles afirmaciones son correctas:<ol class="roman-list" type="I">${statements.map(x=>`<li>${x}</li>`).join('')}</ol>`,...comboOptions('I, II y III',['I y II','II y IV','I, III y IV','II y III','Todas'],c.shuffle),hint:'Las dimensiones internas deben coincidir.',explanation:'I, II y III son correctas; \\(BA\\) solo existe si además \\(p=m\\).',instruction:'Valida las dimensiones antes de multiplicar.'});};
  T.m_equation=c=>{const A=Array.from({length:2},()=>[c.ri(-5,5),c.ri(-5,5)]),X=Array.from({length:2},()=>[c.ri(-4,5),c.ri(-4,5)]),alpha=c.pick([2,3,4]),beta=c.pick([-3,-2,2,3]),B=matAdd(matScale(alpha,X),matScale(beta,A)),i=c.ri(0,1),j=c.ri(0,1);return base(3,'m22-ops',3,'numeric','NIVEL 3 · ECUACIÓN MATRICIAL','m_equation',{prompt:`La ecuación ${math(`${alpha}X${beta>=0?'+':''}${beta}A=B`)} tiene ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Determine ${math(`x_{${i+1}${j+1}}`)}.`,answerValue:X[i][j],hint:`Despeja ${math(`X=\\frac1{${alpha}}(B${beta>=0?'-':'+'}${Math.abs(beta)}A)`)}.`,explanation:display(`X=${mtex(X)},\\qquad x_{${i+1}${j+1}}=${X[i][j]}.`),visual:{kind:'matrixMultiply',A,B,C:X},instruction:'Despeja la matriz desconocida.'});};
  T.m_jordan_power=c=>{const a=c.nz(-4,4),n=c.ri(4,15),A=[[1,a],[0,1]],ans=n*a;return base(3,'m22-ops',3,'numeric','NIVEL 3 · POTENCIA DE JORDAN','m_jordan_power',{prompt:`Sea ${math(`A=${mtex(A)}`)}. Determine la entrada ${math(`(A^{${n}})_{12}`)}.`,answerValue:ans,hint:'Busca el patrón de las potencias de una matriz triangular unipotente.',explanation:display(`A^n=\\begin{bmatrix}1&na\\\\0&1\\end{bmatrix},\\qquad (A^{${n}})_{12}=${n}(${a})=${ans}.`),visual:{kind:'matrixMultiply',A,B:A,C:[[1,ans],[0,1]]},instruction:'Predice una iteración matricial lejana.'});};
  T.m_process=c=>{const P=invertible2(c),x0=[c.ri(1,8),c.ri(1,8)],x1=matVec(P,x0),x2=matVec(P,x1),idx=c.ri(0,1);return base(3,'m33-ops',3,'numeric','NIVEL 3 · PROCESO EN DOS ETAPAS','m_process',{prompt:`Un proceso usa ${math(`P=${mtex(P)}`)} y ${math(`\\mathbf x_0=${v2(x0)}^T`)}. Determine la componente ${idx+1} de ${math('\\mathbf x_2=P^2\\mathbf x_0')}.`,answerValue:x2[idx],hint:'Calcula primero \\(\\mathbf x_1=P\\mathbf x_0\\) y luego \\(\\mathbf x_2=P\\mathbf x_1\\).',explanation:display(`\\mathbf x_1=${v2(x1)}^T,\\qquad \\mathbf x_2=${v2(x2)}^T.`),visual:{kind:'matrixMultiply',A:P,B:[[x0[0]],[x0[1]]],C:[[x1[0]],[x1[1]]]},instruction:'Ejecuta dos actualizaciones sucesivas.'});};
  T.m_transpose=c=>{const A=Array.from({length:3},()=>[c.ri(-5,5),c.ri(-5,5)]),AT=transpose(A);return base(3,'m33-ops',2,'mcq','NIVEL 3 · TRANSPUESTA RECTANGULAR','m_transpose',{prompt:`Determine ${math('A^T')} para ${math(`A=${mtex(A)}`)}.`,...optionSet(AT,[A,matScale(-1,AT),AT.map(r=>[...r].reverse()),[AT[1],AT[0]],AT.map(r=>r.map(Math.abs))],x=>math(mtex(x)),c.shuffle),hint:'Las filas de \\(A\\) se convierten en columnas de \\(A^T\\).',explanation:display(`A^T=${mtex(AT)}.`),visual:{kind:'matrixMultiply',A,C:AT},instruction:'Reorienta las filas como columnas.'});};
  T.m_trace=c=>{const A=invertible2(c),B=invertible2(c),AB=matMul(A,B),ans=AB[0][0]+AB[1][1];return base(3,'m22-ops',3,'numeric','NIVEL 3 · TRAZA DEL PRODUCTO','m_trace',{prompt:`Sean ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Calcule ${math('\\operatorname{tr}(AB)')}.`,answerValue:ans,hint:'Calcula solo las entradas diagonales de \\(AB\\).',explanation:display(`AB=${mtex(AB)},\\qquad \\operatorname{tr}(AB)=${AB[0][0]}+${AB[1][1]}=${ans}.`),visual:{kind:'matrixMultiply',A,B,C:AB},instruction:'Extrae la traza del producto.'});};
  T.m_rect_product=c=>{const A=Array.from({length:2},()=>Array.from({length:3},()=>c.ri(-4,5))),B=Array.from({length:3},()=>Array.from({length:2},()=>c.ri(-4,5))),C=matMul(A,B),i=c.ri(0,1),j=c.ri(0,1);return base(3,'m33-ops',4,'numeric','NIVEL 3 · PRODUCTO RECTANGULAR','m_rect_product',{prompt:`Sean ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Determine ${math(`(AB)_{${i+1}${j+1}}`)}.`,answerValue:C[i][j],hint:'Combina una fila de tres entradas con una columna de tres entradas.',explanation:display(`(AB)_{${i+1}${j+1}}=${C[i][j]}.`),visual:{kind:'matrixMultiply',A,B,C},instruction:'Calcula una entrada del producto rectangular.'});};

  // MUNDO 4 · DETERMINANTES Y SISTEMAS
  T.d_det3=c=>{const a=c.nz(),b=c.ri(-5,5),d=c.nz(),e=c.ri(-5,5),f=c.nz(),A=[[a,b,c.ri(-5,5)],[0,d,e],[0,0,f]],ans=a*d*f;return base(4,'m33-systems',1,'numeric','NIVEL 4 · DETERMINANTE 3×3','d_det3',{prompt:`Calcule ${math(`\\det(A)`)} para ${math(`A=${mtex(A)}`)}.`,answerValue:ans,hint:'La matriz es triangular; multiplica las entradas diagonales.',explanation:display(`\\det(A)=${a}(${d})(${f})=${ans}.`),visual:{kind:'determinant',A,det:ans},instruction:'Calcula el determinante sin expandir de más.'});};
  T.d_properties=c=>{const d=c.nz(-8,8),r=c.pick([-4,-3,-2,2,3,4]),swaps=c.pick([1,2]),ans=d*r*(swaps%2?-1:1);return base(4,'m33-systems',2,'numeric','NIVEL 4 · PROPIEDADES DEL DETERMINANTE','d_properties',{prompt:`Sea ${math('A\\in M_{3\\times3}')} con ${math(`\\det(A)=${d}`)}. La matriz ${math('B')} se obtiene multiplicando una fila por ${math(String(r))} y realizando ${math(String(swaps))} intercambio${swaps===1?'':'s'} de filas. Determine ${math('\\det(B)')}.`,answerValue:ans,hint:'Cada intercambio cambia el signo y el escalamiento multiplica el determinante.',explanation:display(`\\det(B)=(${r})(-1)^{${swaps}}(${d})=${ans}.`),instruction:'Encadena operaciones elementales.'});};
  T.d_param2=c=>{const r1=c.ri(-8,8),r2=c.ri(-8,8);let root1=c.ri(-6,6),root2=c.ri(-6,6);while(root1===root2)root2=c.ri(-6,6);const s=root1+root2,p=root1*root2;const b=c.nz(-5,5),cc=-p/b;if(!Number.isInteger(cc))return T.d_param2(makeContext(c.ri(1,1e9)));const A=[['k',b],[cc,`k${s>=0?'-':'+'}${Math.abs(s)}`]];return base(4,'m22-systems',2,'numeric','NIVEL 4 · PARÁMETRO DEL DETERMINANTE','d_param2',{prompt:`Los valores de ${math('k')} que hacen cero el determinante ${math(`\\det\\begin{bmatrix}k&${b}\\\\${cc}&k${s>=0?'-':'+'}${Math.abs(s)}\\end{bmatrix}`)} tienen cierto producto. Determine ese producto.`,answerValue:p,hint:'Forma el polinomio cuadrático y usa el producto de raíces.',explanation:display(`k^2-${s}k+${p}=0,\\qquad k_1k_2=${p}.`),instruction:'Determina el producto de los parámetros críticos.'});};
  T.d_area=c=>{const u=[c.nz(-8,8),c.nz(-8,8)],v=[c.nz(-8,8),c.nz(-8,8)],ans=Math.abs(u[0]*v[1]-u[1]*v[0]);if(!ans)return T.d_area(makeContext(c.ri(1,1e9)));return base(4,'m22-systems',2,'numeric','NIVEL 4 · ÁREA POR DETERMINANTE','d_area',{prompt:`Calcule el área del paralelogramo generado por ${math(`\\mathbf u=${v2(u)}`)} y ${math(`\\mathbf v=${v2(v)}`)}.`,answerValue:ans,hint:'Toma el valor absoluto del determinante de los vectores.',explanation:display(`\\text{Área}=|${u[0]}(${v[1]})-${u[1]}(${v[0]})|=${ans}.`),visual:{kind:'vectors',u,v},instruction:'Mide el área orientada.'});};
  T.d_augmented_tf=c=>{const vars=c.pick([2,3]),rows=c.pick([2,3,4]),M=Array.from({length:rows},()=>Array.from({length:vars+1},()=>c.ri(-5,7))),truth=c.pick([true,false]);const claimVars=truth?vars:vars+c.pick([-1,1]);return base(4,'m33-systems',2,'tf','NIVEL 4 · MATRIZ AUMENTADA','d_augmented_tf',{prompt:`La matriz aumentada ${math(atex(M))} representa un sistema de ${math(String(rows))} ecuaciones con ${math(String(claimVars))} incógnitas.`,answer:truth,hint:'La última columna contiene los términos independientes.',explanation:`Hay ${rows} filas y ${vars} columnas de coeficientes; la afirmación es ${truth?'verdadera':'falsa'}.`,visual:{kind:'augmented',matrix:M},instruction:'Interpreta la estructura del sistema.'});};
  T.d_classify=c=>{const k=c.nz(-30,30),statements=[`Una fila ${math(`[0\\;0\\;0\\mid${k}]`)} implica inconsistencia.`,`Una fila completamente nula puede acompañar una variable libre.`,`Un pivote en cada columna de variables implica solución única.`,`Dos ecuaciones proporcionales siempre producen inconsistencia.`];return base(4,'m33-systems',3,'roman','NIVEL 4 · CLASIFICACIÓN DE SISTEMAS','d_classify',{prompt:`Sobre matrices aumentadas, son correctas:<ol class="roman-list" type="I">${statements.map(x=>`<li>${x}</li>`).join('')}</ol>`,...comboOptions('I, II y III',['I y II','II y IV','I, III y IV','II y III','Todas'],c.shuffle),hint:'Distingue contradicciones, filas redundantes y pivotes.',explanation:'I, II y III son correctas; ecuaciones proporcionales pueden representar la misma ecuación.',instruction:'Clasifica los resultados de una reducción.'});};
  T.d_system2=c=>{const A=invertible2(c),x=[c.ri(-6,7),c.ri(-6,7)],b=matVec(A,x),ask=c.ri(0,1);return base(4,'m22-systems',3,'numeric','NIVEL 4 · SISTEMA 2×2','d_system2',{prompt:`Resuelva ${display(`\\begin{cases}${A[0][0]}x${A[0][1]>=0?'+':''}${A[0][1]}y=${b[0]},\\\\${A[1][0]}x${A[1][1]>=0?'+':''}${A[1][1]}y=${b[1]}.\\end{cases}`)} Determine ${math(ask===0?'x':'y')}.`,answerValue:x[ask],hint:'Elimina una variable y sustituye en la otra ecuación.',explanation:display(`(x,y)=${v2(x)}.`),visual:{kind:'systemLines',lines:[{m:-A[0][0]/A[0][1],b:b[0]/A[0][1]},{m:-A[1][0]/A[1][1],b:b[1]/A[1][1]}]},instruction:'Encuentra la intersección del sistema.'});};
  T.d_rowop=c=>{const pivot=c.pick([1,-1,2,-2]),below=c.nz(-5,5),factor=-below/pivot;if(!Number.isInteger(factor))return T.d_rowop(makeContext(c.ri(1,1e9)));const M=[[pivot,c.ri(-4,5),c.ri(-4,5),c.ri(-5,8)],[below,c.ri(-4,5),c.ri(-4,5),c.ri(-5,8)],[c.ri(-4,4),c.ri(-4,4),c.ri(-4,4),c.ri(-5,8)]],correct=`R_2\\leftarrow R_2${factor>=0?'+':''}${factor}R_1`;const choices=[`R_2\\leftarrow R_2${-factor>=0?'+':''}${-factor}R_1`,`R_1\\leftarrow R_1${factor>=0?'+':''}${factor}R_2`,`R_3\\leftarrow R_3${factor>=0?'+':''}${factor}R_1`,`R_2\\leftarrow ${Math.abs(factor)||2}R_2-R_1`,`R_1\\leftrightarrow R_2`];return base(4,'m33-systems',4,'operation','NIVEL 4 · OPERACIÓN ELEMENTAL','d_rowop',{prompt:`En ${math(atex(M))}, ¿qué operación elimina la entrada ${math(String(below))} situada debajo del pivote ${math(String(pivot))}?`,...comboOptions(math(correct),choices.map(math),c.shuffle),hint:'Busca un múltiplo de la fila pivote que cancele la primera entrada de la segunda fila.',explanation:`La operación correcta es ${math(correct)}.`,visual:{kind:'gauss',matrix:M,op:correct},instruction:'Selecciona la eliminación exacta.'});};
  T.d_system3=c=>{const {A,x,b,M}=system3FromSolution(c),weights=[c.nz(-3,3),c.nz(-3,3),c.nz(-3,3)],ans=dot(weights,x);return base(4,'m33-systems',4,'numeric','NIVEL 4 · SISTEMA 3×3','d_system3',{prompt:`Resuelva el sistema ${math(atex(M))} y calcule ${math(`${weights[0]}x${weights[1]>=0?'+':''}${weights[1]}y${weights[2]>=0?'+':''}${weights[2]}z`)}.`,answerValue:ans,hint:'Reduce la matriz aumentada hasta obtener tres pivotes.',explanation:display(`(x,y,z)=${v3(x)},\\qquad ${weights[0]}x${weights[1]>=0?'+':''}${weights[1]}y${weights[2]>=0?'+':''}${weights[2]}z=${ans}.`),visual:{kind:'gauss',matrix:M},instruction:'Completa una reducción de tres variables.'});};
  T.d_consistency_param=c=>{const a=c.nz(-5,5),b=c.nz(-5,5),r=c.pick([-4,-3,-2,2,3,4]),d=c.nz(-8,8),ans=r*d,M=[[a,b,d],[r*a,r*b,'k']];return base(4,'m22-systems',3,'numeric','NIVEL 4 · CONSISTENCIA PARAMÉTRICA','d_consistency_param',{prompt:`Determine ${math('k')} para que ${math(atex(M))} represente un sistema consistente.`,answerValue:ans,hint:'La segunda fila de coeficientes es un múltiplo de la primera.',explanation:display(`k=${r}(${d})=${ans}.`),visual:{kind:'augmented',matrix:[[a,b,d],[r*a,r*b,ans]]},instruction:'Encuentra el valor que evita la contradicción.'});};

  // MUNDO 5 · RETOS MIXTOS
  T.mix_projection=c=>{const v=c.pick([[1,1],[1,-1],[2,1],[1,2]]),t=c.nz(-5,5),s=c.nz(-5,5),perp=[-v[1],v[0]],u=addV(scaleV(t,v),scaleV(s,perp)),proj=scaleV(t,v),res=subV(u,proj),ans=norm2(res);return base(5,'mixed-boss',3,'numeric','NIVEL 5 · DESCOMPOSICIÓN ORTOGONAL','mix_projection',{prompt:`Sea ${math(`\\mathbf u=${v2(u)}`)} y ${math(`\\mathbf v=${v2(v)}`)}. Si ${math('\\mathbf u=\\mathbf u_{\\parallel}+\\mathbf u_{\\perp}')} con ${math('\\mathbf u_{\\parallel}=\\operatorname{proj}_{\\mathbf v}(\\mathbf u)')}, calcule ${math('\\|\\mathbf u_{\\perp}\\|^2')}.`,answerValue:ans,hint:'Calcula la proyección, resta y evalúa la norma al cuadrado.',explanation:display(`\\mathbf u_{\\parallel}=${v2(proj)},\\quad \\mathbf u_{\\perp}=${v2(res)},\\quad \\|\\mathbf u_{\\perp}\\|^2=${ans}.`),visual:{kind:'projection',a:u,b:v,proj},instruction:'Descompón la trayectoria en partes paralela y perpendicular.'});};
  T.mix_properties=c=>{const n=c.ri(2,10),pair=c.pick([['A','B'],['P','Q'],['M','N'],['C','D']]),X=pair[0],Y=pair[1],statements=[`${math(`(${X}${Y})^T=${Y}^T${X}^T`)}.`,`Si ${math(`${X}^2=${X}`)}, entonces ${math(`(I_${n}-${X})^2=I_${n}-${X}`)}.`,`Si ${math(`${X}${Y}=0`)}, necesariamente ${math(`${X}=0`)} o ${math(`${Y}=0`)}.`,`Dos matrices diagonales de orden ${math(String(n))} conmutan.`];return base(5,'mixed-boss',3,'roman','NIVEL 5 · PROPIEDADES MATRICIALES','mix_properties',{prompt:`Son correctas:<ol class="roman-list" type="I">${statements.map(x=>`<li>${x}</li>`).join('')}</ol>`,...comboOptions('I, II y IV',['I y II','II y III','I, III y IV','II, III y IV','Todas'],c.shuffle),hint:'La tercera afirmación admite contraejemplos con matrices no nulas.',explanation:'I, II y IV son correctas; III es falsa.',instruction:'Distingue propiedades estructurales.'});};
  T.mix_process=c=>{const P=invertible2(c),x0=[c.ri(2,15),c.ri(2,15)],x1=matVec(P,x0),x2=matVec(P,x1),weights=[c.nz(-3,3),c.nz(-3,3)],ans=dot(weights,x2);return base(5,'mixed-boss',3,'numeric','NIVEL 5 · PROCESO MULTIETAPA','mix_process',{prompt:`Sea ${math(`P=${mtex(P)}`)} y ${math(`\\mathbf x_0=${v2(x0)}^T`)}. Calcule ${math(`${weights[0]}(x_2)_1${weights[1]>=0?'+':''}${weights[1]}(x_2)_2`)}, donde ${math('\\mathbf x_2=P^2\\mathbf x_0')}.`,answerValue:ans,hint:'Calcula \\(x_1\\), luego \\(x_2\\), y al final la combinación pedida.',explanation:display(`\\mathbf x_1=${v2(x1)}^T,\\quad \\mathbf x_2=${v2(x2)}^T,\\quad \\text{valor}=${ans}.`),visual:{kind:'matrixMultiply',A:P,B:[[x0[0]],[x0[1]]],C:[[x1[0]],[x1[1]]]},instruction:'Ejecuta dos etapas y una lectura final.'});};
  T.mix_production=c=>{const {A,x,b,M}=system3FromSolution(c),ans=x.reduce((s,z)=>s+z,0);return base(5,'gauss-boss',4,'numeric','NIVEL 5 · SISTEMA DE PRODUCCIÓN','mix_production',{prompt:`Una producción satisface ${math(`A\\mathbf x=\\mathbf b`)}, con ${math(`A=${mtex(A)}`)} y ${math(`\\mathbf b=${v3(b)}^T`)}. Determine ${math('x_1+x_2+x_3')}.`,answerValue:ans,hint:'Resuelve el sistema por Gauss–Jordan.',explanation:display(`\\mathbf x=${v3(x)}^T,\\qquad x_1+x_2+x_3=${ans}.`),visual:{kind:'augmented',matrix:M},instruction:'Determina el plan total de producción.'});};
  T.mix_det_properties=c=>{const A=invertible3(c),d=det3(A),r=c.pick([-4,-3,-2,2,3,4]),swaps=c.pick([1,2]),ans=d*r*(swaps%2?-1:1);return base(5,'mixed-boss',4,'numeric','NIVEL 5 · DETERMINANTE ENCADENADO','mix_det_properties',{prompt:`Sea ${math(`A=${mtex(A)}`)}. La matriz ${math('B')} se obtiene multiplicando una fila por ${math(String(r))} y realizando ${math(String(swaps))} intercambio${swaps===1?'':'s'} de filas. Calcule ${math('\\det(B)')}.`,answerValue:ans,hint:'Calcula primero \\(\\det(A)\\) y luego aplica los factores de las operaciones.',explanation:display(`\\det(A)=${d},\\qquad \\det(B)=(${r})(-1)^{${swaps}}(${d})=${ans}.`),visual:{kind:'determinant',A,det:d},instruction:'Encadena cálculo y propiedades.'});};
  T.mix_consistency=c=>{const A=invertible3(c),x=[c.ri(-3,5),c.ri(-3,5),c.ri(-3,5)],b=matVec(A,x),M=A.map((r,i)=>[...r,b[i]]),truth=c.pick([true,false]);if(!truth)M[2]=M[0].map((z,i)=>i===3?2*z+1:2*z);return base(5,'gauss-boss',4,'tf','NIVEL 5 · CONSISTENCIA','mix_consistency',{prompt:`El sistema representado por ${math(atex(M))} es consistente.`,answer:truth,hint:'Busca una fila imposible o verifica que la matriz de coeficientes sea invertible.',explanation:truth?`La matriz de coeficientes tiene determinante ${det3(A)} distinto de cero, por lo que hay solución única.`:'La reducción produce una contradicción del tipo \\([0\\;0\\;0\\mid c]\\), con \\(c\\neq0\\).',visual:{kind:'augmented',matrix:M},instruction:'Clasifica el sistema antes del combate.'});};
  T.mix_gauss_op=c=>{const pivot=c.pick([1,-1,2,-2]),below=c.nz(-6,6),f=-below/pivot;if(!Number.isInteger(f))return T.mix_gauss_op(makeContext(c.ri(1,1e9)));const M=[[pivot,c.ri(-4,5),c.ri(-4,5),c.ri(-8,8)],[below,c.ri(-4,5),c.ri(-4,5),c.ri(-8,8)],[c.ri(-4,5),c.ri(-4,5),c.ri(-4,5),c.ri(-8,8)]],correct=`R_2\\leftarrow R_2${f>=0?'+':''}${f}R_1`;return base(5,'gauss-boss',5,'operation','NIVEL 5 · GAUSS–JORDAN','mix_gauss_op',{prompt:`Seleccione la operación que anula la entrada ${math(String(below))} debajo del pivote ${math(String(pivot))} en ${math(atex(M))}.`,...comboOptions(math(correct),[`R_2\\leftarrow R_2${-f>=0?'+':''}${-f}R_1`,`R_1\\leftarrow R_1${f>=0?'+':''}${f}R_2`,`R_3\\leftarrow R_3${f>=0?'+':''}${f}R_1`,`R_1\\leftrightarrow R_2`,`R_2\\leftarrow ${Math.abs(f)||2}R_2-R_1`].map(math),c.shuffle),hint:'Elige un múltiplo que haga cero la primera entrada de la segunda fila.',explanation:`La operación correcta es ${math(correct)}.`,visual:{kind:'gauss',matrix:M,op:correct},instruction:'Ejecuta la primera maniobra de reducción.'});};
  T.mix_rect=c=>{const A=Array.from({length:3},()=>Array.from({length:3},()=>c.ri(-4,5))),B=Array.from({length:3},()=>Array.from({length:2},()=>c.ri(-4,5))),C=matMul(A,B),i=c.ri(0,2),j=c.ri(0,1);return base(5,'mixed-boss',5,'numeric','NIVEL 5 · PRODUCTO RECTANGULAR','mix_rect',{prompt:`Sean ${math(`A=${mtex(A)}`)} y ${math(`B=${mtex(B)}`)}. Determine ${math(`(AB)_{${i+1}${j+1}}`)}.`,answerValue:C[i][j],hint:`Multiplica la fila ${i+1} de \\(A\\) por la columna ${j+1} de \\(B\\).`,explanation:display(`(AB)_{${i+1}${j+1}}=${C[i][j]}.`),visual:{kind:'matrixMultiply',A,B,C},instruction:'Calcula la entrada crítica del producto.'});};
  T.mix_system_expr=c=>{const {x,M}=system3FromSolution(c),w=[c.nz(-4,4),c.nz(-4,4),c.nz(-4,4)],ans=dot(w,x);return base(5,'gauss-boss',5,'numeric','NIVEL 5 · SISTEMA 3×3','mix_system_expr',{prompt:`Resuelva ${math(atex(M))} y determine ${math(`${w[0]}x${w[1]>=0?'+':''}${w[1]}y${w[2]>=0?'+':''}${w[2]}z`)}.`,answerValue:ans,hint:'Reduce la matriz aumentada y sustituye la solución en la expresión.',explanation:display(`(x,y,z)=${v3(x)},\\qquad \\text{valor}=${ans}.`),visual:{kind:'gauss',matrix:M},instruction:'Resuelve y evalúa una combinación lineal.'});};
  T.mix_investment=c=>{const total=c.pick([80,100,120,150]),x=c.pick([10,20,25,30]),ratio=c.pick([2,3]),z=ratio*x,y=total-x-z;if(y<=0)return T.mix_investment(makeContext(c.ri(1,1e9)));const rates=c.pick([[4,6,9],[3,7,10],[5,8,12]]),yieldValue=(rates[0]*x+rates[1]*y+rates[2]*z)/100;return base(5,'gauss-boss',5,'numeric','NIVEL 5 · MODELO DE INVERSIÓN','mix_investment',{prompt:`Se invierten ${math(String(total))} millones en tres alternativas con tasas de ${math(`${rates[0]}\\%`)}, ${math(`${rates[1]}\\%`)} y ${math(`${rates[2]}\\%`)}. El rendimiento total es ${math(texNum(yieldValue))} millones y la tercera inversión es ${math(String(ratio))} veces la primera. Determine la segunda inversión.`,answerValue:y,hint:'Plantea capital total, rendimiento y la relación entre la primera y la tercera inversión.',explanation:display(`(x,y,z)=${v3([x,y,z])}\\text{ millones},\\qquad y=${y}.`),instruction:'Resuelve el modelo financiero completo.'});};

  const BASE_LEVELS={
    1:['v2_combo','v2_norm_unit','v2_norm_param','v2_orth_param','v2_direction','v2_projection','v2_work','v2_difference_norm','v2_displacement','v2_dot_angle'],
    2:['v3_combo','v3_norm_param','v3_dot','v3_orth_param','v3_pythagoras_tf','v3_distance','v3_work','v3_projection_component','v3_linear_param','v3_sum_norm'],
    3:['m_combo','m_product_entry','m_commute_tf','m_dimensions','m_equation','m_jordan_power','m_process','m_transpose','m_trace','m_rect_product'],
    4:['d_det3','d_properties','d_param2','d_area','d_augmented_tf','d_classify','d_system2','d_rowop','d_system3','d_consistency_param'],
    5:['mix_projection','mix_properties','mix_process','mix_production','mix_det_properties','mix_consistency','mix_gauss_op','mix_rect','mix_system_expr','mix_investment']
  };

  // Portales: varias plantillas avanzadas por mundo para evitar ciclos cortos.
  const PORTAL_LEVELS={
    1:['v2_projection','v2_difference_norm','v2_orth_param','v2_work'],
    2:['v3_projection_component','v3_linear_param','v3_orth_param','v3_sum_norm'],
    3:['m_jordan_power','m_equation','m_process','m_rect_product'],
    4:['d_properties','d_param2','d_system3','d_consistency_param'],
    5:['mix_projection','mix_process','mix_det_properties','mix_system_expr','mix_investment']
  };

  // Jefes: combinaciones multi-etapa, regeneradas antes de cada escudo.
  const BOSS_LEVELS={
    1:['v2_combo','v2_projection','v2_difference_norm','v2_displacement'],
    2:['v3_linear_param','v3_projection_component','v3_work','v3_sum_norm'],
    3:['m_equation','m_process','m_trace','m_rect_product'],
    4:['d_properties','d_system3','d_consistency_param','d_rowop'],
    5:['mix_production','mix_det_properties','mix_system_expr','mix_investment']
  };

  function generate(template,seed,overrides={}){
    const fn=T[template];if(!fn)throw new Error(`Plantilla desconocida: ${template}`);
    const q=fn(makeContext(seed));q.template=template;q.variantSeed=seed>>>0;
    return Object.assign(q,overrides);
  }
  function build(seed){
    const qs=[];let id=1;
    Object.entries(BASE_LEVELS).forEach(([level,names])=>names.forEach((name,i)=>qs.push(generate(name,(seed^((+level)*0x9E3779B9)^((i+1)*0x85EBCA6B))>>>0,{id:id++,boss:false}))));
    return qs;
  }
  function buildBlackHole(seed){
    const qs=[];let id=1001;
    Object.entries(PORTAL_LEVELS).forEach(([level,names])=>names.forEach((name,i)=>{const q=generate(name,(seed^((+level)*0xC2B2AE35)^((i+7)*0x27D4EB2D))>>>0,{id:id++,advanced:true});q.badge=`PORTAL · ${q.badge.replace(/^NIVEL \d+ · /,'')}`;q.difficulty=Math.max(4,q.difficulty||1);qs.push(q);}));
    return qs;
  }
  function buildBoss(seed){
    const qs=[];let id=2001;
    Object.entries(BOSS_LEVELS).forEach(([level,names])=>names.forEach((name,i)=>{const q=generate(name,(seed^((+level)*0x165667B1)^((i+11)*0xD3A2646C))>>>0,{id:id++,boss:true});q.badge=(+level===5?`JEFE FINAL · `:`JEFE NIVEL ${level} · `)+q.badge.replace(/^NIVEL \d+ · /,'');q.difficulty=Math.max(+level===5?7:5,q.difficulty||1);qs.push(q);}));
    return qs;
  }
  function regenerate(q,seed){
    if(!q?.template||!T[q.template])return clone(q);
    const preserve={};
    ['id','sourceId','sourceWorld','scene','sector','gradeValue','topicLabel','boss','advanced'].forEach(k=>{if(q[k]!==undefined)preserve[k]=q[k];});
    const fresh=generate(q.template,seed,preserve);
    if(q.badge?.startsWith('PORTAL'))fresh.badge=`PORTAL · ${fresh.badge.replace(/^NIVEL \d+ · /,'')}`;
    if(q.badge?.startsWith('JEFE FINAL'))fresh.badge=`JEFE FINAL · ${fresh.badge.replace(/^NIVEL \d+ · /,'')}`;
    else if(q.badge?.startsWith('JEFE NIVEL'))fresh.badge=`JEFE NIVEL ${q.sourceWorld||fresh.level} · ${fresh.badge.replace(/^NIVEL \d+ · /,'')}`;
    fresh.variantSerial=(q.variantSerial||0)+1;
    return fresh;
  }

  global.NVQuestions={build,buildBlackHole,buildBoss,regenerate};
})(window);
